Cora:
  GAT:
    seed: 1000
    learning_rate: 0.0005
    num_hidden: 256
    coder_hid_num: 36
    num_mid_hidden: 256
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 1
    lambda_edge: -2
    lambda_node: 2
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.4
    num_epochs: 100
    weight_decay: 0.00001
  GCN:
    seed: 1000
    learning_rate: 0.0001
    num_hidden: 512
    coder_hid_num: 12
    num_mid_hidden: 512
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    lambda_edge: 2
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.4
    num_epochs: 100
    weight_decay: 0.00001
CiteSeer:
  GAT:
    seed: 1001
    learning_rate: 0.001
    num_hidden: 256
    coder_hid_num: 36
    num_mid_hidden: 256
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 1
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.9
    num_epochs: 100
    weight_decay: 0.00001
  GCN:
    seed: 1001
    learning_rate: 0.0001 
    num_hidden: 256
    coder_hid_num: 32
    num_mid_hidden: 256
    activation: 'prelu'
    base_model: 'GCNConv'
    num_layers: 2
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.9
    num_epochs: 50
    weight_decay: 0.00001
PubMed:
  GAT:
    seed: 1002
    learning_rate: 0.00005
    num_hidden: 1024
    coder_hid_num: 36
    num_mid_hidden: 1024
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 2
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.7
    num_epochs: 2500
    num_heads: 512
    weight_decay: 0.00001
  GCN:
    seed: 1002
    learning_rate: 0.001
    num_hidden: 256
    coder_hid_num: 32
    num_mid_hidden: 256
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.7
    num_epochs: 2500
    weight_decay: 0.00001
DBLP:
  GAT:
    seed: 1003
    learning_rate: 0.0005
    num_hidden: 256
    coder_hid_num: 36
    num_mid_hidden: 256
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 2
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.7
    num_epochs: 300
    weight_decay: 0.00001
  GCN:
    seed: 1003
    learning_rate: 0.0005
    num_hidden: 256
    coder_hid_num: 32
    num_mid_hidden: 256
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    tau: 0.7
    num_epochs: 250
    weight_decay: 0.00001
WikiCS:
  GAT: 
    seed: 1004
    learning_rate: 0.00001
    num_hidden: 256
    coder_hid_num: 36
    num_mid_hidden: 256
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 2
    tau: 0.7
    num_epochs: 300
    weight_decay: 0.00001
    lambda_edge: 2
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
  GCN: 
    seed: 1005
    learning_rate: 0.00001
    num_hidden: 512
    coder_hid_num: 8
    num_mid_hidden: 512
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    tau: 0.7
    num_epochs: 200
    lambda_edge: -3
    lambda_node: -3
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
    weight_decay: 0.00001
Amazon-Photo:
  GAT: 
    seed: 1006
    learning_rate: 0.000005
    num_hidden: 512
    coder_hid_num: 48
    num_mid_hidden: 512
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 2
    tau: 0.7
    num_epochs: 100
    weight_decay: 0.00001
    lambda_edge: 1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
  GCN: 
    seed: 1007
    learning_rate: 0.000001
    num_hidden: 512
    coder_hid_num: 8
    num_mid_hidden: 512
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    tau: 0.2
    num_epochs: 100
    weight_decay: 0.00001
    lambda_edge: -2
    lambda_node: 2
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
Amazon-Computers:
  GAT: 
    seed: 1008
    learning_rate: 0.00001
    num_hidden: 256
    coder_hid_num: 36
    num_mid_hidden: 256
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 2
    tau: 0.7
    num_epochs: 100
    weight_decay: 0.00001
    lambda_edge: -3
    lambda_node: 3
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
  GCN: 
    seed: 1008
    learning_rate: 0.000001
    num_hidden: 512
    coder_hid_num: 4
    num_mid_hidden: 512
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    tau: 0.2
    num_epochs: 100
    weight_decay: 0.00001
    lambda_edge: -3
    lambda_node: -2
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
Coauthor-CS:
  GAT:
    seed: 1009
    learning_rate: 0.0005
    num_hidden: 256
    coder_hid_num: 2
    num_mid_hidden: 256
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 2
    tau: 0.7
    num_epochs: 400
    weight_decay: 0.00001
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
  GCN:
    seed: 1009
    learning_rate: 0.0005
    num_hidden: 256
    coder_hid_num: 2
    num_mid_hidden: 256
    num_proj_hidden: 256
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    tau: 0.4
    num_epochs: 2000
    weight_decay: 0.00001
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
Coauthor-Phy:
  GAT:
    seed: 110
    learning_rate: 0.0005
    num_hidden: 2
    num_mid_hidden: 2
    activation: 'elu'
    base_model: 'GATConv'
    num_layers: 2
    tau: 0.7
    num_epochs: 400
    weight_decay: 0.00001
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4
  GCN:
    seed: 110
    learning_rate: 0.0005
    num_hidden: 2
    coder_hid_num: 2
    num_mid_hidden: 2
    num_proj_hidden: 2
    activation: 'relu'
    base_model: 'GCNConv'
    num_layers: 2
    tau: 0.4
    num_epochs: 2000
    weight_decay: 0.00001
    lambda_edge: -1
    lambda_node: -1
    edge_p: 0.4
    node_p: 0.4
    k_near: 4